name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        name: ["linux", "mac"]
        include:
          - name: "linux"
            os: ubuntu-latest
          - name: "mac"
            os: macos-latest
  runs-on: ${{ matrix.os }}
  steps:
     - uses: actions/checkout@v1
     - uses: conda-incubator/setup-miniconda@v2
     - name: test
       run: bash test.sh
